from tkinter import *
from pypeg2 import *
import actionbuttons
from statements import *
import sys
import matrix
import math

import os

SMALL_WIN_SIZE = 200
MED_WIN_SIZE = 400
LARGE_WIN_SIZE = 600

SMALL_TEXTBOX_WIDTH = 20
SMALL_TEXTBOX_HEIGHT = 1
MED_TEXTBOX_WIDTH = 35
MED_TEXTBOX_HEIGHT = 8
LARGE_TEXTBOX_WIDTH = 50
LARGE_TEXTBOX_HEIGHT = 10

class ErrorPopup:
    '''
    A pop-up window that gracefully handles Gooey errors.
    Displays the error message to the user and closes when "OK" button is clicked.
    '''
    def __init__(self, message):
        self.message = "Error: " + str(message)
        # Create error popup window
        self.window = Toplevel()
        self.window.title("Error")
        self.window.geometry("%dx%d%+d%+d" % (200, 200, 200, 200))
        # Add message to popup
        messageText = Message(self.window, text=self.message, justify=CENTER)
        messageText.pack()
        # Add "OK" button to popup, that will close popup when clicked
        button = Button(self.window, text="Ok", command=self.window.destroy)
        button.pack()


class GooeyError(Exception):
    def __init__(self, message):
        self.message = message
        ErrorPopup(self.message)
    def __repr__(self):
        return self.message
class Binding:
    '''
    Binding object has four instance variables
    bType - the type of object with regards to "Gooey" ex) Window, Button
    varname - how we identify the object (a string)
    bObject - the actual tkinter object
    params - an optional argument use to take in the parameters of a user defined function
    '''
    bType = None
    varname = None
    bObject = None
    params = None
    frames = None

    def __init__(self,bType,varname,bObject,params,frames):
        '''Sets instance variables: type, name, Tkinter object, and optional parameters'''
        self.bType = bType
        self.varname = varname
        self.bObject = bObject
        self.params = params
        self.frames = frames

    def __repr__(self):
        '''Prints a pretty version of the bindings'''
        prettyStr = "Binding " + str(self.varname) + " of type " + str(self.bType) + "."
        return prettyStr

class Interpreter():
    '''Interpreter class: creates GUI based on the expression given by the user.'''
    gRows = 0
    gColumns = 0

    def __init__(self, target,winBinding,bindings):
        '''Initializes the GUI window'''
        self.window = target
        self.winBinding = winBinding
        self.bindings = bindings

    def setWinBinding(self, b):
        self.winBinding = b

    def interpret(self, ast):
        '''Interprets the Gooey code and creates a GUI in the window.
        It takes in an abstract syntax tree as generated by pypeg, and the current bindings.
        Returns a new list of bindings. '''
        print("AST:", ast)
        for expr in ast:


            '''
-------------------- MAKE --------------------
            '''
            if(expr.__class__.__name__ == "Make"):
                if hasattr(expr, "type"):

                    # Check to see if variable name is already used,
                    # make the object, and add to bindings.
                    if (expr.type == "Window"):
                        self.checkVarname(expr)
                        (w,frames) = self.makeWindow(self.window,expr)
                        binding = self.makeBinding("Window", expr.varname, w,[],frames)
                        self.setWinBinding(binding)
                        self.bindings = self.addBinding(binding)

                    elif(expr.type == "Button"):
                        self.checkVarname(expr)
                        b = self.makeButton(self.winBinding,expr)
                        binding = self.makeBinding("Button", expr.varname, b)
                        self.bindings = self.addBinding(binding)

                    elif(expr.type == "Menu"):
                        self.checkVarname(expr)
                        m = self.makeMenu(self.window,expr,self.bindings)
                        options = self.getOptions(expr)
                        binding = self.makeBinding("Menu", expr.varname, m, options)
                        self.bindings = self.addBinding(binding)

                    elif(expr.type == "MenuItem"):
                        self.checkVarname(expr)
                        mi = self.makeMenuItem(self.window,expr,self.bindings)
                        options = self.getOptions(expr)
                        binding = self.makeBinding("MenuItem", expr.varname, mi, options)
                        self.bindings = self.addBinding(binding)

                    elif(expr.type == "TextBox"):
                        self.checkVarname(expr)
                        t = self.makeTextBox(self.window, expr)
                        binding = self.makeBinding("TextBox", expr.varname, t)
                        self.bindings = self.addBinding(binding)

                    elif(expr.type == "Image"):
                        self.checkVarname(expr)
                        i = self.makeImage(self.window, expr)
                        binding = self.makeBinding("Image", expr.varname, i)
                        self.bindings = self.addBinding(binding)

                    elif(expr.type == "Text"):
                        self.checkVarname(expr)
                        t = self.makeText(self.window, expr)
                        binding = self.makeBinding("Text", expr.varname, t)
                        self.bindings = self.addBinding(binding)

                    elif(expr.type == "FormattedText"):
                        self.checkVarname(expr)
                        ft = self.makeFormattedText(self.window, expr)
                        binding = self.makeBinding("FormattedText", expr.varname, ft)
                        bindings = self.addBinding(binding)

                    elif(expr.type == "Checkboxes"):

                        self.checkVarname(expr)
                        cbSize = 0
                        if hasattr(expr, "attributes"):
                            for item in expr.attributes:
                                if hasattr(item, 'position'):
                                    if hasattr(item.position.value, "r"):
                                        cbRow = int(item.position.value.r)
                                        cbColumn = int(item.position.value.c)
                                    else:
                                        #GET POSITION BY KEYWORD NEEDS THE CHECKBOX OBJECT TO GET THE HEIGHT AND WIDTH
                                        cbRow, cbColumn = self.getPositionByKeyword(w,item.position.value)
                                if hasattr(item, 'size'):
                                    cbSize = item.size.value

                            for item in expr.attributes:
                                if(hasattr(item, 'options')):
                                    i = 0
                                    j = 0
                                    isDefault = False
                                    while(i < len(item.options.options)):
                                        if(item.options.options[i] != ""):
                                            cb = self.makeCheckboxes(self.window,expr,item.options.options[i], j, cbRow, cbColumn)
                                            cb.configure(width=cbSize, height=cbSize)
                                            if (isDefault):
                                                cb.select()
                                            binding = self.makeBinding("Checkboxes", expr.varname, cb)
                                            self.bindings = self.addBinding(binding)
                                            isDefault = False
                                            j += 1
                                        else:
                                            isDefault = True
                                        i += 1

                                elif(hasattr(item, 'title')):
                                    cbTitle = ""
                                    if (hasattr(item.title, 'value')):
                                        cbTitle = item.title.value
                                    ttl = Label(self.window, text=cbTitle)
                                    ttl.place(x=cbRow,y=cbColumn)
                                    if hasattr(item.title, 'var'):
                                        if (item.title.var in bindings):
                                            a = bindings.get(item.title.var).bObject
                                            special = ""

                                            if (a[4] == BooleanValue('true')):
                                                special += "bold "
                                            if (a[5] == BooleanValue('true')):
                                                special += "italic "
                                            if (a[6] == BooleanValue('true')):
                                                special += "underline"
                                            special = special.strip()

                                            font = (a[1], a[2], special)
                                            ttl.configure(text=a[0], fg=a[3], font=font)
                                        else:
                                            raise GooeyError("No formatted text with that name.")
                                    else:
                                        ttl.configure(text=item.title.value)

                                    binding = self.makeBinding("Checkboxes", expr.varname, ttl)
                                    self.bindings = self.addBinding(binding)
                                elif(hasattr(item, 'position')):
                                    pass
                                elif(hasattr(item, 'size')):
                                    pass
                                else:
                                    raise GooeyError("Cannot make Checkboxes with an attribute that Checkboxes does not have.")
                        else:
                            # Use default values
                            pass


                    elif(expr.type == "RadioButtons"):
                        self.checkVarname(expr)
                        selected = False
                        var = IntVar()
                        rbSize = 0
                        if hasattr(expr, "attributes"):
                            for item in expr.attributes:
                                if hasattr(item, 'position'):
                                    if hasattr(item.position.value, "r"):
                                        rbRow = int(item.position.value.r)
                                        rbColumn = int(item.position.value.c)
                                    else:
                                        #GET POSITION BY KEYWORD NEEDS THE OBJECT SO IT CAN GET THE WIDTH AND HEIGHT
                                        rbRow, rbColumn = self.getPositionByKeyword(w, item.position.value)
                                if hasattr(item, 'size'):
                                    rbSize = item.size.value

                            for item in expr.attributes:
                                if(hasattr(item, 'options')):
                                    count = 0
                                    for x in item.options.options:
                                        if (x == ""):
                                            count += 1
                                        if (count == 2):
                                            raise GooeyError("RadioButtons cannot have multiple default selected options.")

                                    i = 0
                                    j = 0
                                    while(i < len(item.options.options)):
                                        if (item.options.options[i] == ""):
                                            selected = True
                                        else:
                                            rb = self.makeRadioButtons(self.window,expr,item.options.options[i], j, rbRow, rbColumn, var)
                                            rb.configure(width=rbSize, height=rbSize)
                                            rb.deselect()
                                            if (selected):
                                                var.set(j)
                                                selected = False
                                            binding = self.makeBinding("RadioButtons", expr.varname, rb)
                                            self.bindings = self.addBinding(binding)
                                            j += 1
                                        i += 1
                                elif(hasattr(item, 'title')):
                                    rbTitle = ""
                                    if (hasattr(item.title, 'value')):
                                        rbTitle = item.title.value
                                    ttl = Label(self.window, text=rbTitle)
                                    ttl.place(x=rbRow,y=rbColumn)
                                    if hasattr(item.title, 'var'):
                                        if (item.title.var in self.bindings):
                                            a = bindings.get(item.title.var).bObject
                                            special = ""

                                            if (a[4] == BooleanValue('true')):
                                                special += "bold "
                                            if (a[5] == BooleanValue('true')):
                                                special += "italic "
                                            if (a[6] == BooleanValue('true')):
                                                special += "underline"
                                            special = special.strip()

                                            font = (a[1], a[2], special)
                                            ttl.configure(text=a[0], fg=a[3], font=font)
                                        else:
                                            raise GooeyError("No formatted text with that name.")
                                    else:
                                        ttl.configure(text=item.title.value)
                                    binding = self.makeBinding("RadioButtons", expr.varname, ttl)
                                    self.bindings = self.addBinding(binding)
                                elif(hasattr(item, 'position')):
                                    pass
                                elif(hasattr(item, 'size')):
                                    pass
                                else:
                                    raise GooeyError("Cannot make RadioButtons with an attribute that RadioButtons does not have.")
                        else:
                            # Use default values
                            pass
                    else:
                        raise GooeyError("Object in Make statement not recognized. Make sure to capitalize the object name.")
                else:
                    raise GooeyError("No type name provided to Make statement.")


                    '''
-------------------- SET --------------------
                    '''
            elif(expr.__class__.__name__ == "GooeySet"):
                print("GOOEY Set")
                if hasattr(expr, "varname"):
                    print("Has Varname: ", expr.varname)
                    print("BINDINGS: ", expr)
                    if expr.varname in self.bindings:
                        print("expr.varname is in bindings")
                        obj = self.bindings[expr.varname]
                        if obj.bType == "Window":
                            win = self.getObject(expr)
                            print("the window", win, self.winBinding)
                            print("BINDINGS", self.bindings)
                            assert win.bType == 'Window'
                            wColorBefore = win.frames.cget('bg')
                            print("HI")
                            w = self.setWindow(win,expr)
                            print("IS THIS PRINTING?", w)
                            print("BYE")
                            wColorAfter = w.frames.cget('bg')
                            if wColorBefore != wColorAfter:
                                print("Colors didn't match")
                                bindings = self.fixButtonPadding(wColorAfter)
                                print("tried to fix button padding")
                            w = self.setWindow(win,expr)

                        elif(obj.bType == "Button"):
                            button = self.getObject(expr)
                            assert button.bType == 'Button'
                            b = self.setButton(button.bObject,self.winBinding, expr)

                        elif(obj.bType == "Menu"):
                            pass

                        elif(obj.bType == "MenuItem"):
                            pass
                        elif(obj.bType == "Text"):
                            t = self.getObject(expr)
                            assert t.bType == 'Text'
                            t = self.setText(t.bObject,self.window, expr) #Change to be self.winbinding

                        elif(obj.bType == "TextBox"):
                            t = self.getObject(expr)
                            assert t.bType == 'TextBox'
                            tbox = t.bObject
                            tbox = self.setTextBox(tbox, self.window, expr) #change to be winbinding
                        else:
                            raise GooeyError("Cannot set variable of type " + str(obj.bType))
                    else:
                        raise GooeyError(str(expr.varname) + " is undefined.")


            # Interprets all function definition statements
            elif(expr.__class__.__name__ == "FunctionDefinition"):
                if hasattr(expr, "funcname"):

                    #Checks bindings to see if function name is already there.
                    #If function isn't already defined, add it to bindings.
                    if expr.funcname not in self.bindings:
                        actions = []
                        for i in range(len(expr.funcaction)):
                            # For each line in the function, get its action
                            # (unwrap the Make, Set, or Return statement from within the Line/LastLine statement)
                            # and replace it in the expression's funcaction attribute
                            action = self.getFunctionLineAction(expr.funcaction[i])
                            actions.append(action)

                        # Fetch formal parameters if function has them
                        formalParams = []
                        if hasattr(expr, "params"):
                            formalParams = expr.params

                        # Add function definition to bindings
                        binding = self.makeBinding("Function", str(expr.funcname), actions, formalParams)
                        self.bindings = self.addBinding(binding)

                    else:
                        raise GooeyError("Sorry, this function name is already used.")
                else:
                    raise GooeyError("Sorry, you need to give your function a name.")

            #Interprets all function calls
            elif(expr.__class__.__name__ == "FunctionCall"):
                print("Function call")
                #Find function with that name
                function = expr.funcname
                if function in self.bindings:

                    # Fetch function from bindings
                    functionBinding = self.bindings[function]

                    # Check if parameter and argument lists are same length
                    if len(expr.params) == len(functionBinding.params):

                        # Create new dictionary of local bindings for the function frame,
                        # and add arguments passed in to it.
                        localBindings = dict()
                        localI = Interpreter(self.winBinding.bObject,self.winBinding, localBindings)

                        # Add arguments passed to function to the local bindings with param names.
                        for paramIndex in range(len(expr.params)):
                            paramName = functionBinding.params[paramIndex]
                            print("param name", paramName)
                            argumentName = expr.params[paramIndex]
                            if argumentName in self.bindings:
                                argument = self.bindings[argumentName]
                                newLocalBinding = localI.makeBinding(argument.bType, paramName, argument.bObject, argument.params, argument.frames)
                                localI.bindings = localI.addBinding(newLocalBinding)
                                if argument.__class__.__name__ == 'Window':
                                    localI.winBinding = newLocalBinding
                                    print("NEW WIN BINDING: ", localI.winBinding)
                                print("Local bindings after", localI.bindings)
                            else:
                                raise GooeyError(str(argumentName) + " is undefined.")
                                return self.bindings


                        # Interpret each line of the function
                        functionCode = functionBinding.bObject
                        print("function code", functionCode)
                        for line in functionCode:
                            if line.__class__.__name__ == "Return":
                                if hasattr(line, "param") and hasattr(expr, "returnTo"):
                                    returnValue = localI.bindings[line.param]
                                    returnedParam = self.makeBinding(returnValue.bType, expr.returnTo, \
                                                                returnValue.bObject, returnValue.params)
                                    self.bindings = self.addBinding(returnedParam)
                            else:
                                print("THE LINE:", line)
                                (localI.bindings, self.winBinding) = localI.interpret([line])

                    else:
                        raise GooeyError("The function "+str(function)+" requires "+str(len(functionBinding.params))+" arguments; you have passed it "+str(len(expr.params))+" arguments.")
                else:
                    raise GooeyError("This function isn't defined.")
            else:
                #Invalid first word
                raise GooeyError("Invalid command. Please start your command with Make, Set, or other valid start commands.")
        print("THESE ARE THE self.bindings: ", self.bindings)
        return (self.bindings,self.winBinding)




    def makeFormattedText(self,w,expr):
        settings = ["Untitled Text", "Times", 12, "black", False, False, False]
        if hasattr(expr, "attributes"):
            for item in expr.attributes:
                print (item)
                if hasattr(item, "text"):
                    settings[0] = item.text.value
                elif hasattr(item, "font"):
                    settings[1] = item.font.name
                elif hasattr(item, "size"):
                    settings[2] = int(item.size.value)
                elif hasattr(item, "color"):
                    settings[3] = item.color.value
                elif hasattr(item, "bold"):
                    settings[4] = item.bold.value
                elif hasattr(item, "italic"):
                    settings[5] = item.italic.value
                elif hasattr(item, "underline"):
                    settings[6] = item.underline.value

        return settings


    '''
-------------------- CHECKBOXES --------------------
    '''
    def makeDefaultCheckboxes(self,w,defaults):
        pass

    def makeCheckboxes(self,w,expr,i,num, r, c):
        r = r + num + 1
        op = Checkbutton(w, text=i, variable=str(num), anchor=W)
        op.grid(row=r, column=c, sticky=N+S+E+W)
        return op

    def setCheckboxes():
        pass

    '''
-------------------- RADIOBUTTONS --------------------
    '''
    def makeDefaultRadioButtons(self,w,defaults):
        pass

    def makeRadioButtons(self,w,expr,i,num, r, c, v):
        r = r + num + 1
        gg = Radiobutton(w, text=i, variable=v, value=num, anchor=W)
        gg.grid(row=r, column=c, sticky=N+S+E+W)
        return gg

    def setRadioButtons():
        pass


    '''
-------------------- TEXT --------------------
    '''
    def makeDefaultText(self,w,defaults):
        tl = Label(w, text = defaults['text'], bg = defaults['color'])
        #needs position and size
        return tl

    def makeText(self,w,expr):
        defaults = self.getAllDefaults("Text")
        tl = self.makeDefaultText(w,defaults)
        #tl = Label(w, text="Text")
        r, c = 0, 0
        hide = False
        if hasattr(expr, "attributes"):
            for item in expr.attributes:
                if hasattr(item, 'text'):
                    if hasattr(item.text, 'var'):
                        if (item.text.var in bindings):
                            a = bindings.get(item.text.var).bObjectspecial = ""

                            if (a[4] == BooleanValue('true')):
                                special += "bold "
                            if (a[5] == BooleanValue('true')):
                                special += "italic "
                            if (a[6] == BooleanValue('true')):
                                special += "underline"
                                special = special.strip()

                            font = (a[1], a[2], special)
                            tl.configure(text=a[0], fg=a[3], font=font)
                        else:
                            raise GooeyError("No formatted text with that name.")
                    else:
                        tl.configure(text=item.text.value)
                elif hasattr(item, 'position'):
                    if hasattr(item.position.value, "r"):
                        r = int(item.position.value.r)
                        c = int(item.position.value.c)
                    else:
                        r, c = self.getPositionByKeyword(tl, item.position.value)
                elif hasattr(item, 'color'):
                    tl.configure(fg=item.color.value)
                elif hasattr(item, 'hidden'):
                    if item.hidden.value == "true":
                        hide = True
                else:
                    raise GooeyError("Can't set Text with an attribute that Text does not have.")
        #tl.grid(row=r, column=c, sticky=N+S+E+W)
        self.checkOccupied(tl, r, c)
        tl.place(x = r, y = c, bordermode="outside")
        print("text x y", tl.winfo_x(), tl.winfo_y())
        if hide:
            tl.place_forget()
        return tl

    def setText(self,tl,w,expr):
        #r, c = 0, 0
        hide = False
        if hasattr(expr, "attributes"):
            for item in expr.attributes:
                if hasattr(item, 'text'):
                    print(item.text.value)
                    tl.configure(text=item.text.value)
                elif hasattr(item, 'position'):
                    if hasattr(item.position.value, "r"):
                        r = int(item.position.value.r)
                        c = int(item.position.value.c)
                    else:
                        r, c = self.getPositionByKeyword(tl, item.position.value)
                    self.checkOccupied(tl, r, c)
                    tl.place(x = r, y = c, bordermode="outside")
                elif hasattr(item, 'color'):
                    tl.configure(fg=item.color.value)
                elif hasattr(item, 'hidden'):
                    if item.hidden.value == 'true':
                        hide = True
                        tl.place_forget()
                    elif item.hidden.value == 'false':
                        #####NOTE: THIS ISN'T GOING TO WORK COME BACK
                        tl.place(x=tl.winfo_x(), y=tl.winfo_y())
                else:
                    raise GooeyError("Can't set Text with an attribute that Text does not have.")
        #tl.grid(row=r, column=c, sticky=N+S+E+W)
        return tl


    '''
-------------------- WINDOWS --------------------
    '''
    def makeDefaultWindow(self,w,defaults):
        '''Makes a window with default attributes'''
        #Configure the window with defaults
        w.deiconify()
        ####NEED TO ADD FONT AND FONTSIZE####
        ####NEED TO DO textcolor as fg = defaults[textcolor]####
        ####NEED TO ADD WINDOW SIZE -- Right now it is just medium size
        #w.geometry('400x400')
        w.title(defaults['title'])
        #w.configure(bg=defaults['color'])
        #self.setWindowColor(w,defaults['color'])
        #Set window size to default size
        w.configure(height=MED_WIN_SIZE, width=MED_WIN_SIZE)
        print("\n\n\nIN MAKE DEFAULTWINDOW")
        print("THIS IS MED_WIN_SIZE", MED_WIN_SIZE)
        print("height and width of w", w.winfo_reqheight(), w.winfo_reqwidth())
        frames = self.setDefaultWindowSize(w, MED_WIN_SIZE, MED_WIN_SIZE)
        print("height and with of frames", frames.winfo_height(),frames.winfo_width())
        self.setWindowColor(frames,defaults['color'])
        #w = self.setDefaultWindowSize(w, MED_WIN_SIZE, MED_WIN_SIZE)

        return (w,frames)
        #return w

    def setDefaultWindowSize(self, w, rows, columns):
        print("Setting default window size to:", rows, columns)
        # frames = []
        # self.gRows = rows
        # self.gColumns = columns
        # backgroundColor = w.cget('bg')
        # for i in range(0,columns):
        #     for j in range(0,rows):
        #         l = Frame(w, height=100, width=100)
        #         l.grid(row = j, column = i)
        #         l.configure(bg = backgroundColor)
        #         frames.append(l)
        # return frames

        ###Leah's messing stuff up here###
        self.gRows = rows
        self.gColumns = columns
        backgroundColor = w.cget('bg')
        l = Frame(w, height = rows, width = columns)
        #l.grid(row = 0, column = 0)
        l.place(x = 0, y = 0, bordermode="outside")
        l.configure(bg = backgroundColor)
        return l
        # w.configure(height = rows*100, width = columns*100)
        # w.grid(row=0,column=0)
        # return w
        ###leah's messing up stops here###

    def setWindowSize(self,w, frames,rows,columns):
    #def setWindowSize(self,w,rows,columns):
        # print("Rows is", rows, "and is of type", type(rows))
        # winsize = rows*columns-1
        #
        # #If we're shrinking the window size, we need to remove the rows and columns of frames
        # #if we're removing rows, then we need to remove indicies of f modded with the removed values
        # #to do this we do modular arithmatic and if the result is bigger than "rows" or "columns", we
        # #remove the frame
        #
        # #if we're growing it, we need to add appropriate rows and columns
        # #We add them
        #
        # for f in range(0,len(frames)):
        #     print(f)
        #     fr = frames[f]
        #     print("This is the current height and width", fr.cget('height'), fr.cget('width'))
        #     fr.grid(row = f//rows, column = f%columns)
        #     frames.append(fr)
        # return frames
        #
        ##Leah is boogering stuff starting here ####
        w.configure(height=rows,width=columns)
        frames.configure(height=rows,width=columns)

        print("configured the frame")
        print(rows)
        print(columns)
        #frames.grid(row = 0, column = 0)
        #frames.place(x = rows, y = columns, bordermode="outside")
        #w.grid(row=0,column=0)
        print("Trouble gridding")
        return frames
        #return w
        ##Leah's boogering done####



    def setWindowColor(self,w,color):
        print("in setwindowcolor")
#        self.gRows = rows
#        self.gColumns = columns
        # for i in range(0,self.gColumns):
        #     for j in range(0,self.gRows):
        #         l = Frame(w, height=100, width=100)
        #         l.grid(row = j, column = i)
        #         l.configure(bg = color)

        ###Leah's shit###
        #NOTE w is now a frame, not the root window##SECOND NOTE NO IT'S NOT#JK it is
        w.configure(bg = color)
        #w.grid(row = 0, column = 0)
        w.place(x = 0, y = 0, bordermode="outside")
        ###STop leah's shit###

    def makeWindow(self,w,expr):
        '''Makes a window given user attributes.
        It should set anything that the user has not specified to the defaults.'''
        #Construct the default window
        defaults = self.getAllDefaults("Window")
        (w,frames) = self.makeDefaultWindow(w,defaults)
        #w = self.makeDefaultWindow(w,defaults)
        #If the user input any attributes, change the default window to reflect that
        if hasattr(expr, "attributes"):
            windowAttributeList = expr.attributes
            for item in windowAttributeList:
                print(item)

                if hasattr(item, 'color'):
                    #w.configure(bg=item.color.value)
                    #self.setWindowColor(w,item.color.value)
                    self.setWindowColor(frames,item.color.value)
                elif hasattr(item,'size'):
                    print("Working on size")
#                    if hasattr(item.size.value, "columns"):
#                        rows = int(item.size.value.rows)
#                        columns = int(item.size.value.columns)
#                        Interpreter.gRows = rows
#                        Interpreter.gColumns = columns
#                        #fill cells with empty space somehow, so the user gets a sense of it actually being a grid
#                        for i in range(0,columns):
#                            for j in range(0,rows):
#                                l = Frame(w, height=100, width=100)
#                                l.grid(row = j, column = i)
#
#                    elif item.size.value[0].isdigit():
#                        size = item.size.value+"x"+item.size.value
#                        w.geometry(size)
#                    else:
#                        print("ITEM.SIZE.LOWER = ", item.size.value.lower())
#                        if item.size.value.lower() == "large":
#                            w.geometry('600x600')
#                        elif item.size.value.lower() == "medium":
#                            print("got to medium")
#                            w.geometry('400x400')
#                        elif item.size.value.lower() == "small":
#                            w.geometry('200x200')



                    if hasattr(item.size.value, "columns"):
                        rows = int(item.size.value.rows)
                        columns = int(item.size.value.columns)
                    else:
                        if item.size.value.lower() == "small":
                            rows = SMALL_WIN_SIZE
                            columns = SMALL_WIN_SIZE
                        elif item.size.value.lower() == "medium":
                            rows = MED_WIN_SIZE
                            columns = MED_WIN_SIZE
                        elif item.size.value.lower() == "large":
                            rows = LARGE_WIN_SIZE
                            columns = MED_WIN_SIZE
#                    Interpreter.gRows = rows
#                    Interpreter.gColumns = columns
#                    #fill cells with empty space somehow, so the user gets a sense of it actually being a grid
#                    for i in range(0,columns):
#                        for j in range(0,rows):
#                            l = Frame(w, height=100, width=100)
#                            l.grid(row = j, column = i)
                    print("hello")
                    frames = self.setWindowSize(w,frames, rows, columns)
                    #w = self.setWindowSize(w,rows,columns)
                    print("What's up")



                elif hasattr(item, 'title'):
                    w.title(item.title.value)
                elif hasattr(item, 'font'):
                    pass
                elif hasattr(item, 'fontSize'):
                    pass
                elif hasattr(item, 'textColor'):
                    pass
        #somewhere in here we need to look and error check that there are only
        #attributes that are supposed to be here
        #return w
        ###Leah change###
        return (w,frames)
        ###Stop leah###




    def setWindow(self,win,expr):
        print("insetwindow")
        print("")
        print("")
        #print("WIN TYPE: ", type(w))
        w = win.bObject
        frames = win.frames
        '''Sets window attributes to those specified by the user.'''
        if hasattr(expr, "attributes"):
            for item in expr.attributes:
                if hasattr(item, 'color'):
                    #self.window.configure(bg=item.color.value)
                    # w.configure(bg=item.color.value)
                    # self.setWindowColor(w,item.color.value)
                    #
                    ###LEAH WAS HERE###
                    print("setting the color maybe")
                    self.setWindowColor(frames,item.color.value)

                    ###BYE LEAH###
                elif hasattr(item,'size'):

                    if hasattr(item.size.value, "columns"):
                        rows = int(item.size.value.rows)
                        columns = int(item.size.value.columns)
                    else:
                        if item.size.value.lower() == "small":
                            rows = SMALL_WIN_SIZE
                            columns = SMALL_WIN_SIZE
                        elif item.size.value.lower() == "medium":
                            rows = MED_WIN_SIZE
                            columns = MED_WIN_SIZE
                        elif item.size.value.lower() == "large":
                            rows = LARGE_WIN_SIZE
                            columns = LARGE_WIN_SIZE
#                    self.gRows = rows
#                    self.gColumns = columns
#                    #fill cells with empty space somehow, so the user gets a sense of it actually being a grid
#                    for i in range(0,columns):
#                        for j in range(0,rows):
#                            l = Frame(w, height=100, width=100)
#                            l.grid(row = j, column = i)
                    self.setWindowSize(w,frames, rows, columns)

                    #TODO: Loop through all existing bindings, redraw them so they aren't covered by the frames

                elif hasattr(item, 'title'):
                    print("SET WINDOW TITLE", type(item.title.value))
                    w.title(item.title.value)
                elif hasattr(item, 'font'):
                    pass
                elif hasattr(item, 'fontSize'):
                    pass
                elif hasattr(item, 'textColor'):
                    pass
                else: # raiseGooeyError
                    err = "Cannot set an attribute that Window does not have. Window only has the following attributes: "
                    for key in self.getAllDefaults('Window').keys():
                        err += str(key) + ', '
                    err = err[:-2]
                    raise GooeyError(err)
        return win




    '''
-------------------- TEXT BOX --------------------
    '''
    def makeDefaultTextBox(self,w,defaults):
        ###STILL NEEDS MORE ###
        '''Makes a TextBox with default attributes'''
        t = Text(w)
        t.insert(END,defaults['text'])
        #need
        #title
        #Position
        #size
        #hidden
        print("Default size for textbox is: ", defaults['size'])
        if defaults['size'] == "small":
            TextBoxWidth = SMALL_TEXTBOX_WIDTH
            TextBoxHeight = SMALL_TEXTBOX_HEIGHT
        elif defaults['size'] == "medium":
            TextBoxWidth = MED_TEXTBOX_WIDTH
            TextBoxHeight = MED_TEXTBOX_HEIGHT
        elif defaults['size'] == "large":
            TextBoxWidth = LARGE_TEXTBOX_WIDTH
            TextBoxHeight = LARGE_TEXTBOX_HEIGHT
        t.configure(width=TextBoxWidth, height = TextBoxHeight, borderwidth=4)
        return t

    def makeTextBox(self,w,expr):
        print("WHYYYYYYY")
        '''Makes a text box with the user defined attributes.'''
        #t = Text(w, height=2, width=30)
        defaults = self.getAllDefaults("TextBox")
        t = self.makeDefaultTextBox(w,defaults)
        r, c = 0, 0
        hide = False
        print("shit")
        if hasattr(expr, "attributes"):
            for item in expr.attributes:
                if hasattr(item, 'text'):
                    t.delete("1.0",END)
                    t.insert(END, item.text.value)
                elif hasattr(item, 'position'):
                    if hasattr(item.position.value, "r"):
                        r = int(item.position.value.r)
                        c = int(item.position.value.c)
                    else:
                        r, c = self.getPositionByKeyword(t, item.position.value)
                elif hasattr(item, 'size'):
                    print("HAS SIZE")
                    if item.size.value == "small":
                        TextBoxWidth = SMALL_TEXTBOX_WIDTH
                        TextBoxHeight = SMALL_TEXTBOX_HEIGHT
                    elif item.size.value == "medium":
                        TextBoxWidth = MED_TEXTBOX_WIDTH
                        TextBoxHeight = MED_TEXTBOX_HEIGHT
                    elif item.size.value == "large":
                        TextBoxWidth = LARGE_TEXTBOX_WIDTH
                        TextBoxHeight = LARGE_TEXTBOX_HEIGHT
                    else:
                        print("ELSE")
                        TextBoxWidth = item.size.value.columns
                        TextBoxHeight = item.size.value.rows
                    t.configure(width=TextBoxWidth, height = TextBoxHeight)
                    print("THIS IS THE TEXTBOX HEIGHT ", TextBoxHeight)
                    print("THIS IS THE TEXTBOX WIDTH ", TextBoxWidth)
                elif hasattr(item, 'hidden'):
                    if item.hidden.value == "true":
                        hide = True
                else:
                    raise GooeyError("Can't make Textbox with an attribute that Textbox does not have.")
                    # Note: should be gooey error
        #t.grid(row=r, column=c, sticky=N+S+E+W)
        self.checkOccupied(t, r, c)
        t.place(x = r, y = c, bordermode="outside")
        if hide:
            t.place_forget(x=t.winfo_x(), y=t.winfo_y()) #Note: this will not work
        return t

    def setTextBox(self,t,w,expr):
        hide = False
        if hasattr(expr, "attributes"):
            for item in expr.attributes:
                if hasattr(item, 'text'):
                    t.delete("1.0",END)
                    t.insert(END, item.text.value)
                elif hasattr(item, 'position'):
                    if hasattr(item.position.value, "r"):
                        r = int(item.position.value.r)
                        c = int(item.position.value.c)
                    else:
                        r, c = self.getPositionByKeyword(t, item.position.value)
                    self.checkOccupied(t, r, c)
                    t.place(x = r, y = c, bordermode="outside")
                elif hasattr(item, 'size'):
                    print("GOT TO SIZE: ", item.size.value)
                    if item.size.value == "small":
                        TextBoxWidth = SMALL_TEXTBOX_WIDTH
                        TextBoxHeight = SMALL_TEXTBOX_HEIGHT
                    elif item.size.value == "medium":
                        TextBoxWidth = MED_TEXTBOX_WIDTH
                        TextBoxHeight = MED_TEXTBOX_HEIGHT
                    elif item.size.value == "large":
                        TextBoxWidth = LARGE_TEXTBOX_WIDTH
                        TextBoxHeight = LARGE_TEXTBOX_HEIGHT
                    else:
                        TextBoxWidth = item.size.value.columns
                        TextBoxHeight = item.size.value.rows
                    t.configure(width=TextBoxWidth, height = TextBoxHeight, borderwidth=4)
                elif hasattr(item, 'hidden'):
                    if item.hidden.value == "true":
                        hide = True
                        t.place_forget() #Note: won't work yet
                    elif item.hidden.value == "false":
                        t.place(x=t.winfo_x(), y=t.winfo_y())
                else:
                    raise GooeyError("Can't set Textbox with an attribute that Textbox does not have.")
                    #Note: raise gooey error
        #t.grid(row=r, column=c, sticky=N+S+E+W)
        return t


    '''
-------------------- BUTTONS --------------------
    '''
    def checkOccupied(self,obj, height, width):
        print("THIS IS THE OBJECT", obj)
        print("THESE ARE THE BINDINGS", self.winBinding.bObject)
        # Checks to make sure nothing is in the space the user is trying to place an object
        # If something is there, raise an error saying which object is there, try again, and do not place object
        print("this is the window height",self.winBinding.bObject.winfo_height())
        winHeight = self.winBinding.bObject.winfo_reqheight()
        winWidth = self.winBinding.bObject.winfo_reqwidth()
#        winHeight = self.winBinding.bObject.winfo_height()
#        winWidth = self.winBinding.bObject.winfo_width()


        print("OBJECT SIZE", obj.winfo_width(), )
        if obj.winfo_width()+width > winWidth:
            raise GooeyError("Object placed outside window. Choose a new width")
        if obj.winfo_height()+height > winHeight:
            raise GooeyError("Object placed outside window. Choose a new height")
        #Go through the bindings and make sure we're not placing on top of other objects
        #See children of root window
        for child in self.winBinding.frames.winfo_children():
            if child != obj:
                print(child.winfo_x(), child.winfo_y())
            # else:
        #    print("Everything is hunky dory")
        #Check and raise an error if the object will appear outside the edge of the window, so fuck you


    def makeDefaultButton(self, w, defaults):
        '''Makes a button with default attributes'''
        #This is the current background color of the window
        #We need this to correct for padding issues on the mac
        hB = w.cget('bg')
        b = Button(w, highlightbackground = hB)
        #Need to add in position, size, color?
        b.configure(text=defaults['text'])
        return b


    def makeButton(self,w,expr):
        print("Look here's w in makeButton", w)
        win = w.frames

        '''Makes a button by taking in the window the button should be made in
        and the expression given by the user.'''
        defaults = self.getAllDefaults('Button')
        b = self.makeDefaultButton(win,defaults)
        r, c = 0, 0
        hide = False
        print("GOT TO MAKE BUTTON: ", r, c)
        if hasattr(expr, "attributes"):
            buttonAttributeList = expr.attributes
            for item in buttonAttributeList:
                if hasattr(item, 'color'):
                    b.configure(bg=item.color.value)
                if hasattr(item, 'text'):
                    if hasattr(item.text, 'var'):
                        if (item.text.var in bindings):
                            a = bindings.get(item.text.var).bObject
                            special = ""

                            if (a[4] == BooleanValue('true')):
                                special += "bold "
                            if (a[5] == BooleanValue('true')):
                                special += "italic "
                            if (a[6] == BooleanValue('true')):
                                special += "underline"
                            special = special.strip()

                            font = (a[1], a[2], special)
                            b.configure(text=a[0], fg=a[3], font=font)
                        else:
                            raise GooeyError("No formatted text with that name.")
                    else:
                        b.configure(text=item.text.value)
                elif hasattr(item,'size'):
                    b.configure(width=item.size.value)
                    b.configure(height=item.size.value)
                elif hasattr(item,'position'):
                    if hasattr(item.position.value, "r"):
                        r = int(item.position.value.r)
                        c = int(item.position.value.c)
                        print("R", r)
                        print("C", c)
                    else:
                        r, c = self.getPositionByKeyword(b, item.position.value)

                # These are the action statements
                elif hasattr(item, 'action'):
                    #Cast action to string, otherwise you cannot find right action
                    #This is temporary until I can call the action as a direct line in the command
                    act = str(item.action.funcname)
                    print("THIS IS THE ACTION: ", act)
       
                    
                    a = actionbuttons.findAction(item)
                    if actionbuttons.checkActions(a):
                        b.configure(command=lambda: actionbuttons.callAction(win,item,act))
                    else: #Gooey code function
                        print("in da else")
                        args = []
                        if hasattr(item.action, "arguments"):
                            args = item.action.arguments
                            print("ARGS", args)
                        b.configure(command=lambda: self.gooeyCallAction(a, args)) #figure out params for this
                        #run this like we're running a function definition
                            
                        
                    # else:
                    #     print("You have entered a command that is not defined")
                elif hasattr(item, 'hidden'):
                    if item.hidden.value == "true":
                        hide = True
        print("R:", r, "C", c)
        #b.grid(row=r, column=c, sticky=N+S+E+W)
        self.checkOccupied(b, r, c)
        print("\n\nMade it through check occupied!")
        b.place(x = r, y = c, bordermode="outside")
        if hide:
            b.place_forget() #Note won't work yet
        return b
    
    
    def gooeyCallAction(self,action, params):
        #Create an interpreter with the bindings and winbinding of this interpreter
        #Execute the code in this button action
        #Modify global bindings accordingly
#        function = expr.funcname
#        if function in self.bindings:
#
#            # Fetch function from bindings
#            functionBinding = self.bindings[function]
#
#            # Check if parameter and argument lists are same length
#            if len(expr.params) == len(functionBinding.params):

                # Create new dictionary of local bindings for the function frame,
                # and add arguments passed in to it.
#            localBindings = dict()
#            localI = Interpreter(self.winBinding.bObject,self.winBinding, localBindings)
#            (self.bindings,self.winBindings) = localI.interpret(
        print("PARAMS:", params, "LEN PARAMS", len(params))
        gooeyStr = "run "+str(action)+"("
        for param in range(len(params)):
            gooeyStr += str(params[param])
            if param < len(params)-1:
                gooeyStr += ", "
        gooeyStr += ")."
        print(gooeyStr)
        ast = parse(gooeyStr, Program)
        newI = Interpreter(self.winBinding.bObject, self.winBinding, self.bindings)
        (self.winBinding, self.bindings) = newI.interpret(ast)


    def setButton(self,b,win,expr):
        w = win.frames
        '''Sets button based on user attributes.'''
        buttonAttributeList = expr.attributes
        for item in buttonAttributeList:
            if hasattr(item, 'color'):
                b.configure(bg=item.color.value)
            if hasattr(item, 'text'):
                if hasattr(item.text, 'var'):
                    if (item.text.var in bindings):
                        a = bindings.get(item.text.var).bObject
                        special = ""

                        if (a[4] == BooleanValue('true')):
                            special += "bold "
                        if (a[5] == BooleanValue('true')):
                            special += "italic "
                        if (a[6] == BooleanValue('true')):
                            special += "underline"
                        special = special.strip()

                        font = (a[1], a[2], special)
                        b.configure(text=a[0], fg=a[3], font=font)
                    else:
                        raise GooeyError("No formatted text with that name.")
                else:
                    b.configure(text=item.text.value)
            elif hasattr(item,'size'):
                b.configure(width=item.size.value)
                b.configure(height=item.size.value)
            elif hasattr(item,'position'):
                if hasattr(item.position.value, "r"):
                    r = int(item.position.value.r)
                    c = int(item.position.value.c)
                else:
                    r, c = self.getPositionByKeyword(b, item.position.value)
                #b.grid(row=r, column=c, sticky=N+S+E+W)
                self.checkOccupied(b, r, c)
                b.place(x=r, y=c)
#            elif hasattr(item, 'action'):
#                # print(item)
#                action = str(item.action.value)
#                # print("AKLSJDHFKLAJHFH")
#                # print(item.action.value)
#                # if action == 'write':
#                #     b.configure(command=lambda: actionbuttons.Actions.write(item.action.text))
#                # elif action == 'close':
#                #     b.configure(command=lambda: actionbuttons.Actions.close(w))
#                # elif action == 'colorChange':
#                #     b.configure(command=lambda: actionbuttons.Actions.windowColorChange(w, item.action.color))
#                #     print("interpreter")
#                #a = actionbuttons.Actions.callAction(w,item)
#                a = actionbuttons.findAction(item)
#                #w = a[0]
#                #item = a[1]
#                b.configure(command=lambda: actionbuttons.callAction(w,item,action))

            elif hasattr(item, 'action'):
                    #Cast action to string, otherwise you cannot find right action
                    #This is temporary until I can call the action as a direct line in the command
                    action = str(item.action.funcname)
                    print("THIS IS THE ACTION: ", action)
       
                    
                    a = actionbuttons.findAction(item)
                    if actionbuttons.checkActions(a):
                        b.configure(command=lambda: actionbuttons.callAction(win,item,action))
                    else: #Gooey code function
                        args = []
                        if hasattr(item, "argument"):
                            args = item.argument
                        b.configure(command=lambda: self.gooeyCallAction(a, args)) #figure out params for this
                        #run this like we're running a function definition
                            
                        
                    # else:
                    #     print("You have entered a command that is not defined")
            elif hasattr(item, 'hidden'):
                if item.hidden.value == 'false':
                    b.place(x=b.winfo_x(), y=b.winfo_y()) #Note: won't work yet
                elif item.hidden.value == 'true':
                    b.place_forget() #Note: won't work yet
        return b

    def fixButtonPadding(self,color):
        print("in fixbuttonpadding")
        '''Fixes the padding around the buttons'''
        for i in self.bindings.keys():
            if self.bindings[i].bType == "Button":
                print("Got a button")
                self.bindings[i].bObject.configure(highlightbackground = color)
        return self.bindings








    '''
-------------------- MENUS --------------------
    '''
#    def makeDefaultMenu(self,w,defaults):
#        pass
    def makeMenu(self,w,expr):
        rootMenu = None
        children = w.winfo_children()
        for c in children:
            if type(c).__name__ == "Menu":
                rootMenu = c
        w.config(menu=rootMenu)
        return rootMenu

#    def makeDefaultMenuItem(self,w,defaults):
#        pass

    def setMenu():
        pass

    def makeMenuItem(self,w,expr):
        menuItem = None
        rootMenu = None
        children = w.winfo_children()
        for c in children:
            if type(c).__name__ == "Menu":
                rootMenu = c

        #check if menu item has already been defined as a child of some other menu or menuitem
        for key in self.bindings:
            if self.bindings[key].bType == "Menu":
                if expr.varname in self.bindings[key].params:
                    #binding found, add to submenu to rootMenu
                    subMenu = Menu(self.bindings[key].bObject, tearoff=0)
                    #get the text attribute
                    subMenuText = "Undefined"
                    for item in expr.attributes:
                        if hasattr(item,'text'):
                            subMenuText = item.text.value
                    self.bindings[key].bObject.add_cascade(label=subMenuText,menu=subMenu)

                    for item in expr.attributes:
                        if hasattr(item, 'options'):
                            for v in item.options.value:
                                print(v)
                                '''
                                action = str(v)
                                a = actionbuttons.findAction(v)
                                subMenu.add_command(label=v.text,command=lambda: actionbuttons.callAction(w,v,action))
                                '''


                    menuItem = subMenu
                    w.config(menu=self.bindings[key].bObject)

        return menuItem

        def setMenuItem():
            pass


    '''
-------------------- IMAGES - not in window right now! --------------------
    '''
    def makeDefaultImage(self,w,defaults):
        pass
    def makeImage(self, w, expr):
        '''Makes a images with the user defined attributes.'''
        defaults = self.getAllDefaults("Image")
        #(i,l) = self.makeDefaultImage(w,defaults)
        r, c = 0, 0
        print("W is type: ", w)
        if hasattr(expr, "attributes"):
            for item in expr.attributes:
                if hasattr(item, 'source'):


                    ######## Images only work when you read in from text file, otherwise source path is different

                    #directory = os.getcwd()
                    #print("OS : ", os.getcwd())
                    #directory = str(sys.path[0])
                    #directory = directory.append('/apple.gif')
                    #print("CURRENT WORKING DIR IS: ", directory+'/apple.gif')
                    #print("DIRECTORY IS: ", sys.path.append(os.path.dirname(os.path.abspath(__file__)))
                    #i = PhotoImage(file=open(directory+'/apple.gif'))


                    i = PhotoImage(file=item.source.value)
                    l = Label(w, image=i)
                    l.image = i
                else:
                    i = PhotoImage(file="gooeylogosmallest.gif")
                    raise GooeyError("Cannot make Image with attribute Image does not have.") # Note: change gooey error
                if hasattr(item, 'position'):
                        if hasattr(item.position.value, "r"):
                            r = int(item.position.value.r)
                            c = int(item.position.value.c)
                        else:
                            r, c = self.getPositionByKeyword(i, item.position.value)
        #l.grid(row=r, column=c, sticky=N+S+E+W)
        self.checkOccupied(l, r, c)
        l.place(x = r, y = c, bordermode="outside")
        if hide:
            l.grid_remove
        return l

    def setImage():
        pass




    '''
-------------------- HELPER METHODS --------------------
    '''
    def makeBinding(self,t,v,o,p=[],f=[]):
        '''Makes a binding for the object.'''
        binding = Binding(t,v,o,p,f)
        return binding

    def addBinding(self,b):
        '''Takes a binding and adds to the dictionary of bindings.'''
        self.bindings[b.varname] = b
        return self.bindings

    def getFunctionLineAction(self, expr):
        '''Interprets one line of a function, returns the action that line does.'''
    #        if(expr.__class__.__name__ == "Return"):
    #            return expr
    #        else:
        return expr.lineAction

    '''#Make the binding associated with this function
    #The object will be the parameters passed in and the function action (in a tuple)
    def makeFunction(self,w, expr):
        pass'''

    #this should maybe take in parameters
    #expects "run" then a user defined function name
    #replaces , separating gooey instructions and adds period at end
    #Makes a temporary binding relating to parameters and then gets rid of that parameter
#    def runFunction(self,function,localBindings):
#        #Run function should create local bindings maybe?????????????????
#        #print("\n\n I'm running runFunction!")
#        print("got to runFunction")
#        functionCode = self.bindings[function].bObject #We need to make this proper gooey code
#        print("This is the functionCode: ", functionCode)
#        newBindings = localBindings
#        #self.binding = localBindings
#        #print("New Bindings: ", newBindings)
#        for i in range(len(functionCode)-1):
#        #for action in functionCode:
#            print("Here's the action", functionCode[i])
#
#            ##########################OH SHIT, JAMAICA IS TRYING SOMETHING#############################
#            #newBindings = self.interpret([functionCode[i]], newBindings)
#            newBindings = self.interpret([functionCode[i]])
#            ###############################END TRIAL, PROBS BAD #####################################
#            # newBindings = self.interpret(action, newBindings)
#
#            #print("New Bindings: ", newBindings)
#        return newBindings
#        # funStr = ''
#        # for i in functionCode:
#        #     funStr = funStr + " " + i
#        # funStr = funStr[1:] + "."
#        # #parse the function code and pass the parsed code as the ast
#        # localAst = parse(funStr,Program)
#        # newBindings = self.interpret(localAst,localBindings)
#        # return newBindings


    def getOptions(self,expr):
        '''Get list of options, ie: make MenuItem with options [red green blue]. '''
        for item in expr.attributes:
            if hasattr(item, 'options'):
                print(item.options.value)
                return item.options.value
            else:
                return None


    def getAllDefaults(self, typeName):
        '''Given a Gooey type name, like "Window" or "Button", consult our matrix
        and return the predetermined default attributes for that type'''
        defaults = {}
        for i in range(0,matrix.NUM_ATTRIBUTES):
            defaultAttr = matrix.getDefault(typeName, i)
            defaults[matrix.AttrName(i).name] = defaultAttr
            #Need to figure out how to return these
        return defaults

    def checkVarname(self,exp):
        if hasattr(exp, "varname"):
            #if expr.varname in bindings:
            if exp.varname in self.bindings:
                raise GooeyError(str(exp.varname)+" already defined.")


    def getObject(self,exp):
        if exp.varname in self.bindings:
            return self.bindings[exp.varname]
        else:
            raise GooeyError(str(exp.varname)+" undefined.")


    def getPositionByKeyword(self, obj, keyword):
        winwidth = self.winBinding.bObject.winfo_reqwidth()
        winheight = self.winBinding.bObject.winfo_reqheight()
        objwidth = obj.winfo_reqwidth()
        objheight = obj.winfo_reqheight()

        if keyword == "center":
            w = winwidth/2 - objwidth/2
            h = winheight/2 - objheight/2
        elif keyword == "top":
            w = winwidth/2 - objwidth/2
            h = 0
        elif keyword == "bottom":
            w = winwidth/2 - objwidth/2
            h = winheight - objheight - 1
        elif keyword == "left":
            w = 0
            h = winheight/2 - objheight/2
        elif keyword == "right":
            w = winwidth - objwidth
            h = winheight/2-objheight/2
        elif keyword == "topleft":
            w = 0
            h = 0
        elif keyword == "topright":
            w = winwidth - objwidth
            h = 0
        elif keyword == "bottomleft":
            w = 0
            h = winheight - objheight - 1
        elif keyword == "bottomright":
            w = winwidth - objwidth
            h = winheight - objheight - 1
        return w, h

#    def extractTextValue(self, value):
#        words = re.findall(r'[\w\d\.]+', value)
#        return ' '.join(words)
